name: Check Pull Requests on main

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read
  pull-requests: write

jobs:
  npm_test_and_lint:
    uses: ./.github/workflows/reusable_test_and_lint.yml
  terraform_check_and_validate:
    uses: ./.github/workflows/reusable_terraform_check.yml
