name: Test & Lint Pull Requests on main

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_test:
    uses: ./.github/workflows/reusable_test_and_lint.yml
